#######################################################
#                 server config                       #
#######################################################
server:
  port: 80
  servlet:
    context-path: /

#######################################################
#                 application config                  #
#######################################################
spring:
  application:
    name: gofl-blog
  # 关闭缓存
  thymeleaf:
    mode: HTML
    cache: false
  # 关闭mvc的favicon
  mvc:
    favicon:
      enabled: false
  #datasouce config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gofl_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: 123
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 30000



#######################################################
#                 logging config                      #
#######################################################


#######################################################
#                 mybatis config                      #
#######################################################
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mapper/**/*Mapper.xml
  type-aliases-package: com.gofl.**.domain


